openapi: 3.0.3
info:
  version: '81.0'
  title: 'KTCA(Kona Traffic Controller API)'
  description: |
    
    트레이서 API 컴포넌트

    |컴포넌트|url|설명|
    |-----|-----|-----|
    |KTCA|http://118.33.122.28:21002|KTC API 서버|


    #### KTC 에서 제어하는 대상인 Zone에 대한 정보를 관리할 수 있다
    #### 현재 Zone 의 상세한 상태 정보를 조회할 수 있다  
    #### DBMT 에서 응답해주는 현재 WALLET 서버, DB 서버의 정보를 관리할 수 있다
    
    <br>
    
    # 관련문서
    
    | 구분| 내용 |
    |-----|-----|
    | KCT 프로젝트 소개 | https://konawiki.konai.com/pages/viewpage.action?pageId=386013831 |
    | KCT 프로젝트 설명 | https://konawiki.konai.com/pages/viewpage.action?pageId=383936079 |
    | KTCA api 문서 위키 | https://konawiki.konai.com/pages/viewpage.action?pageId=386015669 |
    
    <br>
  
    # 주요정의
    
    |명칭|의미|
    |-----|-----|
    |Zone|KTC 에서 트래픽을 조절할 대상|
    
    

servers:
  - url: http://118.33.122.28:21002

tags:
  - name: Zone
  - name: Metrics

x-tagGroups:
  - name: KTC-API
    tags:
      - Zone
      - Metrics

paths:
  /zone/{zoneId}:
    get:
      summary: Zone 단일 조회
      tags:
        - Zone
      operationId: getZoneInfo
      description: |
        path 에 입력한 zone 에 대한 정보를 조회한다 <br>
      parameters:
        - $ref: '#/components/parameters/path-zoneId'
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetZoneInfoResDto'
        '400':
          description: |
            실패

            |코드|의미|
            |-----|-----|
            |||
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

    delete:
      summary: Zone 단일 삭제
      tags:
        - Zone
      operationId: deleteZoneInfo
      description: |
        path 에 입력한 zone 에 대한 정보를 삭제한다 <br>
      parameters:
        - $ref: '#/components/parameters/path-zoneId'
      responses:
        '200':
          description: '성공'
        '400':
          description: |
            실패

            |코드|의미|
            |-----|-----|
            |||
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /zone:
    post:
      summary: Zone 단일 등록 / 수정
      tags:
        - Zone
      operationId: postZoneInfo
      description: |
        zone 을 등록 / 수정한다 <br>
        requestBody 에 zoneId 을 전달한 경우 > zone 신규 등록 <br>
        requestBody 에 zoneId 을 전달하지 않은 경우 > zone 수정 <br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostZoneInfoReqDto'
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostZoneInfoResDto'
        '400':
          description: |
            실패

            |코드|의미|
            |-----|-----|
            |||
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /zone/list:
    get:
      summary: Zone 리스트 조회
      tags:
        - Zone
      operationId: getAllZoneInfo
      description: |
        현재 등록되어 있는 모든 zone 을 조회한다 <br>
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllZoneInfoResDto'
        '400':
          description: |
            실패

            |코드|의미|
            |-----|-----|
            |||
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


components:
  parameters:
    ##### path
    path-zoneId:
      in: path
      name: zoneId
      required: true
      schema:
        type: string
        example: 'KZ202504111730001234'
        description: |
          Zone 을 특정짓는 아이디 <br>
          KCTA 에서 직접 생성 > KZ + yyyyMMddHHmiss + random 4자리
                

    ##### query
    query-zoneId:
      in: query
      name: zoneId
      required: true
      schema:
        type: string
      example: "KZ202504111730001234"
      description: |
        Zone 을 특정짓는 아이디 <br>
        KCTA 에서 직접 생성 > KZ + yyyyMMddHHmiss + random 4자리


  schemas:
    ##### common schema start
    pageNo:
      type: integer
      description: 페이징 번호
      example: 1

    pageSize:
      type: integer
      description: 페이징 크기
      example: 10

    totalElements:
      type: integer
      description: 전체 항목 수
      example: 100

    totalPages:
      type: integer
      description: 전체 페이징 수
      example: 10

    created:
      type: string
      description: "생성일시(yyyymmddHH24miss)"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    updated:
      type: string
      description: "수정일시(yyyymmddHH24miss)"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    yyyymmddHH24miss:
      type: string
      description: "yyyymmddHH24miss"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    yyyymmdd:
      type: string
      description: "yyyymmdd"
      pattern: "^[0-9]*$"
      minLength: 8
      maxLength: 8
      example: "20231011"

    tid:
      type: string
      description: "tid"
      example: "231011165643-bdd69ad"

    createdYyyymmdd:
      type: string
      description: "생성일자(yyyymmdd)"
      pattern: "^[0-9]*$"
      example: "20231011"

    fromDate:
      type: string
      description: "시작일(yyyymmdd)"
      pattern: "^[0-9]*$"
      example: "20231011"

    toDate:
      type: string
      description: "종료일(yyyymmdd)"
      pattern: "^[0-9]*$"
      example: "20231011"

    creatorId:
      type: string
      description: "생성 hostname(컴포넌트명) - 없으면 CLIENT"
      example: "CLIENT"

    updaterId:
      type: string
      description: "수정 hostname(컴포넌트명) - 없으면 CLIENT"
      example: "CLIENT"

    aspId:
      type: string
      description: "ASP ID"
      maxLength: 15
      minLength: 15
      pattern: "^[0-9]*$"
      example: "000137000000000"
      default: "000000000000000"

    aspIdWithoutDefault:
      type: string
      description: "ASP ID"
      maxLength: 15
      minLength: 15
      pattern: "^[0-9]*$"
      example: "000137000000000"

    yn:
      type: string
      description: "Y/N"
      enum:
        - Y
        - N
      example: 'N'
      default: 'N'

    kaId:
      type: string
      description: "KA ID"
      maxLength: 15
      pattern: "^[0-9]*$"
      example: "410312830116600"

    kaName:
      type: string
      description: "KA 명"
      example: "고양"

    zoneId:
      type: string
      example: "KZ202504111730001234"
      description: |
        Zone 을 특정짓는 아이디 <br>
        KCTA 에서 직접 생성 > KZ + yyyyMMddHHmiss + random 4자리

    zoneName:
      type: string
      description: "Zone 이름"
      example: "인천 충전화면"

    threshold:
      type: integer
      description: "임계치"
      example: 100000

    zoneStatus:
      type: string
      enum:
        - SUSPENDED
        - ACTIVATED
        - DELETED
      description: |
        Zone 의 상태
        
        |타입|의미|
        |----|----|
        |SUSPENDED|정지 : 현재 사용되고 있지 않은 Zone(초기 등록 시 기본값)|
        |ACTIVATED|활성화 : 현재 트래픽의 제어가 되고 있는 Zone|
        |DELETED|삭제 : 미사용되는 Zone|

    zoneActivationTime:
      type: string
      description: |
        Zone 이 활성화되는 시간(yyyymmddHH24miss)
      example: "20250501000000"

    entrantsCount:
      type: integer
      description: "Zone 의 현재 진입자 수"
      example: 95000

    waitingCount:
      type: integer
      description: "Zone 의 현재 대기자 수"
      example: 5000

    maxWaitingDuration:
      type: integer
      description: |
        Zone 에 진입하기 위해 대기했던 최대 대기 시간(분단위) <br>
        = 가장 최근에 접속한 사람이 기다린 시간 <br>
        = 마지막 토큰이 소진된 시간 <br>
      example: 45

    ##### api dto start
    ErrorResponseDto:
      type: object
      properties:
        returnCode:
          type: string
          description: Error Code
        returnMessage:
          type: string
          description: Error Message
        printMessage:
          type: string
          description: Error Print Message

    GetZoneInfoResDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/zoneId'
        name:
          $ref: '#/components/schemas/zoneName'
        threshold:
          $ref: '#/components/schemas/threshold'
        activationTime:
          $ref: '#/components/schemas/zoneActivationTime'
        status:
          $ref: '#/components/schemas/zoneStatus'
        entrantsCount:
          $ref: '#/components/schemas/entrantsCount'
        waitingCount:
          $ref: '#/components/schemas/waitingCount'
        maxWaitingDuration:
          $ref: '#/components/schemas/maxWaitingDuration'
        created:
          $ref: '#/components/schemas/created'
        updated:
          $ref: '#/components/schemas/updated'
        updaterId:
          $ref: '#/components/schemas/updaterId'

    GetAllZoneInfoResDto:
      type: object
      properties:
        zoneInfoList:
          type: array
          items:
            $ref: '#/components/schemas/GetZoneInfoResDto'

    PostZoneInfoReqDto:
      type: object
      required:
        - zoneName
        - threshold
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'
        zoneName:
          $ref: '#/components/schemas/zoneName'
        threshold:
          $ref: '#/components/schemas/threshold'
        zoneActivationTime:
          $ref: '#/components/schemas/zoneActivationTime'

    PostZoneInfoResDto:
      type: object
      required:
        - zoneId
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'