openapi: 3.0.3
info:
  version: '81.0'
  title: 'KTCA(Kona Traffic Controller API)'
  description: |
    #### KTC API 컴포넌트
    
    | Component | URL | 설명 |
    | :---: | :---: | --- |
    | KTCA | `http://118.33.122.28:21002` | KTC API 처리 서버 |
    
    - `KTC` 트래픽 제어 대상 Zone 정보 관리
    - `KTC` 트래픽 제어 Zone 현황 모니터링  
    - WALLET, OracleDB 상태 수집기 `DBMT` 컴포넌트로부터 정보 제공받아 트래픽 허용 임계치 조절
    
    #### 관련문서
    
    - [KTC 기능정의서](https://konawiki.konai.com/pages/viewpage.action?pageId=386013831)
    - [KTC 프로젝트 Wiki](https://konawiki.konai.com/display/KonaCardDevelopment/KTC-APIs)
    
    #### 주요 정의
      
    | 명칭 | 의미 |
    | :---: | --- |
    | Zone | KTC 트래픽 제어를 위한 대상 |

servers:
  - url: http://118.33.122.28:21002

tags:
  - name: V1.Zone Management
  - name: V1.Zone Monitoring

x-tagGroups:
  - name: KTC-API
    tags:
      - V1.Zone Management
      - V1.Zone Monitoring

paths:
  /api/v1/zone:
    post:
      summary: 트래픽 제어 Zone 단일 등록 / 수정
      tags:
        - V1.Zone Management
      operationId: saveZone
      description: |
        트래픽 제어 Zone 등록/생성<br>
        - 요청 `zoneId` 정보 미포함인 경우, 신규 등록 처리<br>
        - 요청 `zoneId` 정보 포함인 경우, 정보 수정 처리<br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1SaveZoneRequest'
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1SaveZoneResponse'
        '400':
          description: |
            Failed

            | 코드 | 의미 |
            |:---:|---|
            | - | - |
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/zone/{zoneId}:
    get:
      summary: 트래픽 제어 Zone 단일 조회
      tags:
        - V1.Zone Management
      operationId: findZone
      description: |
        트래픽 제어 Zone 정보 단일 조회
      parameters:
        - $ref: '#/components/parameters/path-zoneId'
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1FindZoneResponse'
        '400':
          description: |
            Failed

            | 코드 | 의미 |
            |:---:|---|
            | - | - |
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: 트래픽 제어 Zone 단일 삭제
      tags:
        - V1.Zone Management
      operationId: deleteZone
      description: |
        트래픽 제어 Zone 정보 단일 삭제
      parameters:
        - $ref: '#/components/parameters/path-zoneId'
      responses:
        '200':
          description: 'Ok'
        '400':
          description: |
            Failed

            | 코드 | 의미 |
            |:---:|---|
            | - | - |
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/zone/list:
    get:
      summary: 트래픽 제어 Zone 목록 조회
      tags:
        - V1.Zone Management
      operationId: findZoneList
      description: |
        트래픽 제어 Zone 정보 목록 조회
      parameters:
        - $ref: '#/components/parameters/query-page'
        - $ref: '#/components/parameters/query-size'
        - $ref: '#/components/parameters/query-zoneId'
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1FindAllZoneResponse'
        '400':
          description: |
            Failed

            | 코드 | 의미 |
            |:---:|---|
            | - | - |
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/zone/monitoring:
    get:
      summary: 트래픽 제어 Zone 현황 조회
      tags:
        - V1.Zone Monitoring
      operationId: zoneMonitoring
      description: |
        트래픽 제어 Zone 트래픽 현황 조회
      parameters:
        - $ref: "#/components/parameters/query-zoneId"
      responses:
        '200':
          description: '성공'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1ZoneMonitoringResponse'
        '400':
          description: |
            Failed

            | 코드 | 의미 |
            |:---:|---|
            | - | - |
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    ##### path
    path-zoneId:
      in: path
      name: zoneId
      required: true
      schema:
        type: string
        example: 'KZ202504111730001234'
        description: |
          트래픽 제어 Zone 고유 식별 ID<br>
          `KCTA` 자체 생성 > `KZ + yyyyMMddHHmmss + random 4자리`

    ##### query
    query-zoneId:
      in: query
      name: zoneId
      required: false
      schema:
        type: string
      example: "KZ202504111730001234"
      description: |
        트래픽 제어 Zone 고유 식별 ID<br>
        `KCTA` 자체 생성 > `KZ + yyyyMMddHHmmss + random 4자리`

    query-page:
      in: query
      name: page
      required: false
      schema:
        type: integer
      example: 0
      description: Page 번호

    query-size:
      in: query
      name: size
      required: false
      schema:
        type: integer
      example: 10
      description: Page 크기

  schemas:
    ##### common schema start
    first:
      type: boolean
      description: 첫 Page 여부
      example: true

    last:
      type: boolean
      description: 마지막 Page 여부
      example: false

    number:
      type: integer
      description: Page 번호
      example: 0

    numberOfElements:
      type: integer
      description: Page 당 항목 수
      example: 20

    size:
      type: integer
      description: Page 크기
      example: 10

    totalPages:
      type: integer
      description: 전체 페이징 수
      example: 10

    totalElements:
      type: integer
      description: 전체 항목 수
      example: 100

    pageable:
      type: object
      properties:
        first:
          $ref: '#/components/schemas/first'
        last:
          $ref: '#/components/schemas/last'
        number:
          $ref: '#/components/schemas/number'
        numberOfElements:
          $ref: '#/components/schemas/numberOfElements'
        size:
          $ref: '#/components/schemas/size'
        totalPages:
          $ref: '#/components/schemas/totalPages'
        totalElements:
          $ref: '#/components/schemas/totalElements'

    fromDate:
      type: string
      description: "시작일(yyyymmdd)"
      pattern: "^[0-9]*$"
      example: "20231011"

    toDate:
      type: string
      description: "종료일(yyyymmdd)"
      pattern: "^[0-9]*$"
      example: "20231011"

    created:
      type: string
      description: "생성일시(yyyymmddHH24miss)"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    updated:
      type: string
      description: "수정일시(yyyymmddHH24miss)"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    yyyyMMddHHmmss:
      type: string
      description: "yyyyMMddHHmmss"
      pattern: "^[0-9]*$"
      example: "20231011155700"

    yyyyMMdd:
      type: string
      description: "yyyyMMdd"
      pattern: "^[0-9]*$"
      minLength: 8
      maxLength: 8
      example: "20231011"

    ##### property schema start
    zoneId:
      type: string
      example: "KZ202504111730001234"
      description: |
        트래픽 제어 Zone 고유 식별 ID<br>
        `KCTA` 자체 생성 > `KZ + yyyyMMddHHmmss + random 4자리`

    zoneAlias:
      type: string
      description: Zone 별칭
      example: "KTC TEST ZONE"

    zoneStatus:
      type: string
      enum:
        - ACTIVE
        - BLOCKED
        - DELETED
      description: |
        Zone 상태
        | 구분 | 내용 |
        |:----:|----|
        | ACTIVE | Zone 트래픽 제어 활성화 상태 |
        | BLOCKED | Zone 트래픽 진입 전체 차단 상태 |
        | DELETED | Zone 삭제 상태 |
      example: "ACTIVE"

    threshold:
      type: integer
      description: Zone 임계값
      example: 2000

    activationTime:
      type: string
      description: 트래픽 제어 Zone 활성화 시간(yyyyMMddHHmmss)
      example: "20250501000000"

    waitingCount:
      type: integer
      description: Zone 대기자 수
      example: 1500

    entryCount:
      type: integer
      description: Zone 진입자 수
      example: 1000

    estimatedClearTime:
      type: integer
      description: Zone 대기 해소 예상 시간
      example: 60000

    ##### api dto start
    ResultResponse:
      type: object
      properties:
        status:
          type: string
          description: 응답 결과 상태
        code:
          type: string
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          description: 응답 결과 상태
        code:
          type: string
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지

    ##### request/response schema start
    V1SaveZoneRequest:
      type: object
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'
        zoneAlias:
          $ref: '#/components/schemas/zoneAlias'
        threshold:
          $ref: '#/components/schemas/threshold'
        activationTime:
          $ref: '#/components/schemas/activationTime'
        status:
          $ref: '#/components/schemas/zoneStatus'

    V1SaveZoneResponse:
      type: object
      required:
        - zoneId
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'
        result:
          $ref: '#/components/schemas/ResultResponse'

    V1ZoneData:
      type: object
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'
        zoneAlias:
          $ref: '#/components/schemas/zoneAlias'
        threshold:
          $ref: '#/components/schemas/threshold'
        activationTime:
          $ref: '#/components/schemas/activationTime'
        status:
          $ref: '#/components/schemas/zoneStatus'
        created:
          $ref: '#/components/schemas/created'
        updated:
          $ref: '#/components/schemas/updated'

    V1FindZoneResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/V1ZoneData'
        result:
          $ref: '#/components/schemas/ResultResponse'

    V1FindAllZoneResponse:
      type: object
      properties:
        pageable:
          $ref: '#/components/schemas/pageable'
        content:
          type: array
          items:
            $ref: '#/components/schemas/V1FindZoneResponse'
        result:
          $ref: '#/components/schemas/ResultResponse'

    V1ZoneMonitoringData:
      type: object
      properties:
        zoneId:
          $ref: '#/components/schemas/zoneId'
        zoneAlias:
          $ref: '#/components/schemas/zoneAlias'
        threshold:
          $ref: '#/components/schemas/threshold'
        activationTime:
          $ref: '#/components/schemas/activationTime'
        status:
          $ref: '#/components/schemas/zoneStatus'
        waiting:
          type: object
          properties:
            entryCount:
              $ref: '#/components/schemas/entryCount'
            waitingCount:
              $ref: '#/components/schemas/waitingCount'
            estimatedClearTime:
              $ref: '#/components/schemas/estimatedClearTime'

    V1ZoneMonitoringResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/V1ZoneMonitoringData'
        result:
          $ref: '#/components/schemas/ResultResponse'